export const counties = [
  "Dutchess",
  "Orange",
  "Putnam",
  "Rockland",
  "Sullivan",
  "Ulster",
  "Westchester",
];

export const colors = {
  Dutchess: "#ff6384",
  Orange: "#ff9f40",
  Putnam: "#ffcd56",
  Rockland: "#4bc0c0",
  Sullivan: "#36a2eb",
  Ulster: "#9966ff",
  Westchester: "#c9cbcf",
  Region: "#000",
};

export const listProps = [
  "newCases",
  "totalTests",
  "percentPositive",
  "rolling7Avg",
  "rollingCaseAvg",
];

export const regionDict = {
  "Western New York": [
    "Allegany",
    "Cattaraugus",
    "Chautauqua",
    "Erie",
    "Niagara",
  ],
  "Finger Lakes": [
    "Genesee",
    "Livingston",
    "Monroe",
    "Ontario",
    "Orleans",
    "Seneca",
    "Wayne",
    "Wyoming",
    "Yates",
  ],
  "Southern Tier": [
    "Broome",
    "Chemung",
    "Chenango",
    "Delaware",
    "Schuyler",
    "Steuben",
    "Tioga",
    "Tompkins",
  ],
  "Central New York": ["Cayuga", "Cortland", "Madison", "Onondaga", "Oswego"],
  "Mohawk Valley": [
    "Fulton",
    "Herkimer",
    "Montgomery",
    "Oneida",
    "Otsego",
    "Schoharie",
  ],
  "North Country": [
    "Clinton",
    "Essex",
    "Franklin",
    "Hamilton",
    "Jefferson",
    "Lewis",
    "St. Lawrence",
  ],
  "Capital Region": [
    "Albany",
    "Columbia",
    "Greene",
    "Saratoga",
    "Schenectady",
    "Rensselaer",
    "Warren",
    "Washington",
  ],
  "Mid-Hudson": [
    "Dutchess",
    "Orange",
    "Putnam",
    "Rockland",
    "Sullivan",
    "Ulster",
    "Westchester",
  ],
  "New York City": ["Bronx", "Kings", "New York", "Richmond", "Queens"],
  "Long Island": ["Nassau", "Suffolk"],
};
