

export const colors = [
   "#ff6384",
   "#ff9f40",
   "#ffcd56",
   "#a5c78B",
   "#4bc0c0",
   "#36a2eb",
   "#9966ff",
   "#b199e7",
   "#c9cbcf",
];

export const listProps = [
  "newCases",
  "totalTests",
  "percentPositive",
  "rolling7Avg",
  "rollingCaseAvg",
];

export const regionDict = {
  "Western-New-York": [
    "Allegany",
    "Cattaraugus",
    "Chautauqua",
    "Erie",
    "Niagara",
  ],
  "Finger-Lakes": [
    "Genesee",
    "Livingston",
    "Monroe",
    "Ontario",
    "Orleans",
    "Seneca",
    "Wayne",
    "Wyoming",
    "Yates",
  ],
  "Southern-Tier": [
    "Broome",
    "Chemung",
    "Chenango",
    "Delaware",
    "Schuyler",
    "Steuben",
    "Tioga",
    "Tompkins",
  ],
  "Central-New-York": ["Cayuga", "Cortland", "Madison", "Onondaga", "Oswego"],
  "Mohawk-Valley": [
    "Fulton",
    "Herkimer",
    "Montgomery",
    "Oneida",
    "Otsego",
    "Schoharie",
  ],
  "North-Country": [
    "Clinton",
    "Essex",
    "Franklin",
    "Hamilton",
    "Jefferson",
    "Lewis",
    "St. Lawrence",
  ],
  "Capital-Region": [
    "Albany",
    "Columbia",
    "Greene",
    "Saratoga",
    "Schenectady",
    "Rensselaer",
    "Warren",
    "Washington",
  ],
  "Mid-Hudson": [
    "Dutchess",
    "Orange",
    "Putnam",
    "Rockland",
    "Sullivan",
    "Ulster",
    "Westchester",
  ],
  "New-York-City": ["Bronx", "Kings", "New York", "Richmond", "Queens"],
  "Long-Island": ["Nassau", "Suffolk"],
};
